BRANCH_IS_PRIMARY=true
BRANCH_NAME=main
BUILD_DISPLAY_NAME=#6
BUILD_ID=6
BUILD_NUMBER=6
BUILD_TAG=jenkins-ROBOSHOP-catalogue-main-6
BUILD_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/6/
CI=true
EXECUTOR_NUMBER=1
GIT_BRANCH=main
GIT_COMMIT=5ca09d2f1c45e23ab1305610ac5be6596216f70f
GIT_PREVIOUS_COMMIT=5ca09d2f1c45e23ab1305610ac5be6596216f70f
GIT_PREVIOUS_SUCCESSFUL_COMMIT=5ca09d2f1c45e23ab1305610ac5be6596216f70f
GIT_URL=https://github.com/imran806721/catalogue.git
HOME=/var/lib/jenkins
HUDSON_COOKIE=133c368b-2103-478c-b797-7f21c9dbdac5
HUDSON_HOME=/var/lib/jenkins
HUDSON_SERVER_COOKIE=af0e9c9242d7ac67
HUDSON_URL=http://jenkins.devops90s.shop:8080/
INVOCATION_ID=4347a0ec0dc74fe38e5e1b05e8a6e327
JENKINS_HOME=/var/lib/jenkins
JENKINS_NODE_COOKIE=1a6740b7-7d8f-499a-86fe-1fabe27e89c8
JENKINS_SERVER_COOKIE=durable-69c722b0a04e2addcebb3be28d8eba1a09fc80320f0823bdb7308360977dd415
JENKINS_URL=http://jenkins.devops90s.shop:8080/
JOB_BASE_NAME=main
JOB_DISPLAY_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/display/redirect
JOB_NAME=ROBOSHOP/catalogue/main
JOB_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/
JOURNAL_STREAM=8:42092
LANG=C.UTF-8
LOGNAME=jenkins
NODE_LABELS=built-in
NODE_NAME=built-in
NOTIFY_SOCKET=/run/systemd/notify
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD=/var/lib/jenkins/workspace/ROBOSHOP_catalogue_main
RUN_ARTIFACTS_DISPLAY_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/6/display/redirect?page=artifacts
RUN_CHANGES_DISPLAY_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/6/display/redirect?page=changes
RUN_DISPLAY_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/6/display/redirect
RUN_TESTS_DISPLAY_URL=http://jenkins.devops90s.shop:8080/job/ROBOSHOP/job/catalogue/job/main/6/display/redirect?page=tests
SHLVL=2
STAGE_NAME=Build
SYSTEMD_EXEC_PID=3245
USER=jenkins
WORKSPACE=/var/lib/jenkins/workspace/ROBOSHOP_catalogue_main
WORKSPACE_TMP=/var/lib/jenkins/workspace/ROBOSHOP_catalogue_main@tmp
_=/usr/bin/printenv
component=catalogue
library.jenkins-shared-library.version=main
project=roboshop